In [35]:
import pandas as pd
import numpy as np
roomdf = pd.read_csv('C:\\GootTeamProject\\TMSTROOM_DATA_TABLE.csv')
roomdf

               R_NAME    R_DETAIL
0         소노캄 거제 101호  쾌적한 공간입니다.
1         소노캄 거제 102호  쾌적한 공간입니다.
2         소노캄 거제 103호  쾌적한 공간입니다.
3     스탠포드 호텔 서울 101호  쾌적한 공간입니다.
4     스탠포드 호텔 서울 102호  쾌적한 공간입니다.
5     스탠포드 호텔 서울 103호  쾌적한 공간입니다.
6        그라벨호텔제주 101호  쾌적한 공간입니다.
7        그라벨호텔제주 102호  쾌적한 공간입니다.
8        그라벨호텔제주 103호  쾌적한 공간입니다.
9     센텀 프리미어 호텔 101호  쾌적한 공간입니다.
10    센텀 프리미어 호텔 102호  쾌적한 공간입니다.
11    센텀 프리미어 호텔 103호  쾌적한 공간입니다.
12  오크우드 프리미어 인천 101호  쾌적한 공간입니다.
13  오크우드 프리미어 인천 102호  쾌적한 공간입니다.
14  오크우드 프리미어 인천 103호  쾌적한 공간입니다.
15       호텔 디에디션 101호  쾌적한 공간입니다.
16       호텔 디에디션 102호  쾌적한 공간입니다.
17       호텔 디에디션 103호  쾌적한 공간입니다.
18    스탠포드 호텔 서울 103호  쾌적한 공간입니다.
19      씨 크루즈 호텔 101호  쾌적한 공간입니다.
20      씨 크루즈 호텔 102호  쾌적한 공간입니다.
21      씨 크루즈 호텔 103호  쾌적한 공간입니다.
22        쏠비치 진도 101호  쾌적한 공간입니다.
23        쏠비치 진도 102호  쾌적한 공간입니다.
24        쏠비치 진도 103호  쾌적한 공간입니다.

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

tfidf_matrix_room=tfidf.fit_transform(roomdf['R_DETAIL'])
tfidf_matrix_room.shape

(25, 2)

In [37]:
from sklearn.metrics.pairwise import linear_kernel
cosine_sim_room=linear_kernel(tfidf_matrix_room,tfidf_matrix_room)
cosine_sim_room

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
indices_room=pd.Series(roomdf.index,index=roomdf['R_NAME']).drop_duplicates()
indices_room

R_NAME
소노캄 거제 101호           0
소노캄 거제 102호           1
소노캄 거제 103호           2
스탠포드 호텔 서울 101호       3
스탠포드 호텔 서울 102호       4
스탠포드 호텔 서울 103호       5
그라벨호텔제주 101호          6
그라벨호텔제주 102호          7
그라벨호텔제주 103호          8
센텀 프리미어 호텔 101호       9
센텀 프리미어 호텔 102호      10
센텀 프리미어 호텔 103호      11
오크우드 프리미어 인천 101호    12
오크우드 프리미어 인천 102호    13
오크우드 프리미어 인천 103호    14
호텔 디에디션 101호         15
호텔 디에디션 102호         16
호텔 디에디션 103호         17
스탠포드 호텔 서울 103호      18
씨 크루즈 호텔 101호        19
씨 크루즈 호텔 102호        20
씨 크루즈 호텔 103호        21
쏠비치 진도 101호          22
쏠비치 진도 102호          23
쏠비치 진도 103호          24
dtype: int64

In [39]:
indices_room['쏠비치 진도 102호']

23

In [45]:
def get_recommendations_room(R_NAME,cosine_sim_room=cosine_sim_room):
    #영화 제목을 통해서 전체 데이터 기준 그 영화의 index값을 가져오기
    idx_room=indices_room[R_NAME]
    sim_scores_room=list(enumerate(cosine_sim_room[idx_room]))
    # 코사인 유사도매트릭스 cosine_sim에서 idx에 해당하는 데이터를 (idx, 유사도)
    sim_scores_room=sorted(sim_scores_room,key=lambda x:x[1],reverse=True)
    # 코사인 유사도 기준으로 내림차순정렬
    sim_scores_room=sim_scores_room[1:7] 
    # 자신을 제외한 7개의 추천 영화를 슬라이싱
    # 추천서적목록 인덱스 정보 추출
    return roomdf['R_NAME'].iloc[[i[0] for i in sim_scores_room]]

print(get_recommendations_room('쏠비치 진도 102호'));

1        소노캄 거제 102호
2        소노캄 거제 103호
3    스탠포드 호텔 서울 101호
4    스탠포드 호텔 서울 102호
5    스탠포드 호텔 서울 103호
6       그라벨호텔제주 101호
Name: R_NAME, dtype: object